services:
  - type: web
    name: kintai-check
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: TESSDATA_PREFIX
        value: /usr/share/tesseract-ocr/5/tessdata
